# myvalues.yaml
# Overrides to avoid using devops-secret
license:
  secret:
    devOps: null  # disables the devops-secret reference

git:
  secret:
    name: null

env:
  container:
    envFrom: []  # ensures no extra configMaps/secrets are added

# Admin credentials
pingfederate-admin:
  administrativeAccounts:
    items:
      - username: Administrator
        password: "Atharv@123PG09"

  # Tell Helm to create the secret with this password
  adminPasswordSecret:
    name: pf-admin-password
    key: PING_IDENTITY_ADMIN_PASSWORD
